version: '3.9'

services:

  mlflow-server:
    image: python:3.13-slim
    container_name: mlflow-server

    working_dir: /app

    volumes:
      - .:/app
      - mlflow-data:/app/mlruns

    command: >
      sh -c "
      pip install mlflow &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      "

    ports:
      - "5000:5000"

    networks:
      - mlops-network

  model-serving:
    image: harga-minyak-serving:latest

    depends_on:
      - mlflow-server

    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge

volumes:
  mlflow-data: